name: WorldguardChecker
version: '${project.version}'
main: com.kamesuta.worldguardchecker.WorldguardChecker
api-version: 1.19
authors: [ Kamesuta ]
depend:
  - WorldGuard

permissions:
  worldguardchecker.bypass:
    description: Bypass WorldguardChecker
    default: op